- name: Install dnsmasq for caching DNS queries
  action: apt name=dnsmasq state=installed

- name: Write custom dnsmasq.conf
  copy: src=dnsmasq.conf
        dest=/etc/dnsmasq.conf
        owner=root
        group=root
        mode=0644
        backup=yes
  notify:
    - restart dnsmasq

- name: Make sure dnsmasq is running
  service: name=dnsmasq state=running
