- name: Install redis
  apt: name=redis-server state=installed

- name: Write custom redis.conf
  copy: src=redis.conf
        dest=/etc/redis/redis.conf
        owner=root
        group=root
        mode=0644
        backup=yes
  notify:
    - restart redis

- name: Increase redis max open files
  lineinfile: dest=/etc/default/redis-server line="ULIMIT=500000"
  notify:
    - restart redis

- name: Make sure redis is running
  service: name=redis-server state=running

- name: Write iptables.conf
  copy: src=iptables.conf
        dest=/etc/iptables.conf
        owner=root
        group=root
        mode=0644
        backup=yes

- name: Write custom rc.local
  copy: src=rc.local
        dest=/etc/rc.local
        owner=root
        group=root
        mode=0755
        backup=yes

- name: Load iptables rules from rc.local
  action: shell /etc/rc.local
